permalink: /:id
timezone: Asia/Seoul
future: true
# Plugins (previously gems:)
plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-include-cache
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-include-cache
  - jekyll-redirect-from


locale                   : "ko-KR"
title                    : "당신의 마음을 전하는 목소리, 스윗금귤"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "AJ스윗금귤"
description              : "여러분의 일상의 시작과 끝을 따뜻하게 다독여줄, AJ 스윗금귤입니다. 저의 목소리가 여러분에게 닿아서 힘이 되면 좋겠어요. 오늘 하루가 행복으로 가득차기를 바라요. 언제든 힘들면 쉬러와요. 전 항상 여기 있어요."
url                      : "https://sweettodaynote.github.io"
baseurl                  : # 서브 경로가 있는 경우 기재

category_list:
  - video
  - photo
  - article
