permalink: /:id
timezone: Asia/Seoul
future: true
plugins:
  - jekyll-redirect-from

title: 당신의 마음을 전하는 목소리, 스윗금귤
description: 여러분의 일상의 시작과 끝을 따뜻하게 다독여줄, AJ 스윗금귤입니다. 저의 목소리가 여러분에게 닿아서 힘이 되면 좋겠어요. 오늘 하루가 행복으로 가득차기를 바라요. 언제든 힘들면 쉬러와요. 전 항상 여기 있어요.
